stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: registry.gitlab.com/soft-dev-edu/MEPHIDEV/simple_app

build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $DOCKER_IMAGE

deploy_staging:
  stage: deploy
  environment:
    name: staging
  script:
    - kubectl apply -f k8s/deployment.yaml
    - kubectl apply -f k8s/service.yaml1~stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: registry.gitlab.com/soft-dev-edu/MEPHIDEV/simple_app

build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $DOCKER_IMAGE

deploy_staging:
  stage: deploy
  environment:
    name: staging
  script:
    - kubectl apply -f k8s/deployment.yaml
    - kubectl apply -f k8s/service.yaml
