name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create SSH directory
      run: mkdir -p ~/.ssh

    - name: Add GitHub to known hosts
      run: ssh-keyscan -H github.com >> ~/.ssh/known_hosts

    - name: Deploy to server via SSH
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        port: 22
        script: |
          # Создаем директорию, если её нет
          mkdir -p /var/www/simple_app
          cd /var/www/simple_app

          # Если это первый раз, клонируем репозиторий
          if [ ! -d ".git" ]; then
            git clone git@github.com:Isochrone13/simple_app.git .
          fi

          # Обновляем код
          git pull origin main

          # Устанавливаем зависимости
          npm install

          # Запускаем приложение через PM2
          pm2 start simple_app.js --name simple_app || pm2 restart simple_app
